#!/usr/bin/sh
if [ "$1" = "pdf" ]; then
    python3 generators/pdfgen.py
fi
if [ "$1" = "json" ]; then
    python3 generators/jsongen.py
fi
if [ "$1" = "csv" ]; then
    python3 generators/csvgen.py
fi
if [ "$1" = "xlsx" ]; then
    python3 generators/xlsxgen.py
fi
if [ "$1" = "ods" ]; then
    python3 generators/odsgen.py
fi
if [ "$1" = "all" ]; then
    echo "Generating PDF..."
    python3 generators/pdfgen.py
    echo "Generating JSON..."
    python3 generators/jsongen.py
    echo "Generating CSV..."
    python3 generators/csvgen.py
    echo "Generating XLSX..."
    python3 generators/xlsxgen.py    
    echo "Generating ODS..."
    python3 generators/odsgen.py
fi

